
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_SERVER_ADDRESS:http://localhost:3306/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost
