
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_SERVER_ADDRESS:http://localhost:8762/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost
okta:
  oauth2:
    issuer: https://dev-23088527.okta.com/oauth2/default
    audience: api://default
